# Use the official Rust image as the base image
FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Use version 1.93.0 of Rust as the base image
#FROM rust:1.93.0

SHELL ["/bin/bash", "-c"]

# Install the rust package dependencies
RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Switch to the vscode user and set the working directory
ARG USERNAME=vscode
USER $USERNAME
WORKDIR /home/$USERNAME

# Install rustup and the latest stable Rust toolchain for that user
#RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable

# Install rustup and Rust 1.93.0 
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
    && source "$HOME/.cargo/env" \
    && rustup install 1.93.0 \
    && rustup default 1.93.0

# Update PATH for all users
ENV PATH="/home/$USERNAME/.cargo/bin:$PATH"

# Install Helm
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# Switch back to root to install kubectl
USER root
# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && install -m 0755 kubectl /usr/local/bin/kubectl

# Switch back to vscode user
USER vscode